### ISSUE TITLE
Почти

### ISSUE THREAD

**Issue by HukuTa45** [DK-0x3/RPM_1#1]
https://github.com/DK-0x3/RPM_1/blob/a127394b5e6614a19c998909404bbf52d502f7a5/WpfApp1/MainWindow.xaml.cs#L21

Так именуются приватные переменные
Почти идеально)

**Comment by DK-0x3** [comment]
А, да, у меня она была приватной но потом я решил убрать приватность а переименовать забыл.

**Comment by HukuTa45** [comment]
А почему решил? 
Тут как раз она и должна быть приватной, ты же не будешь ее использовать вне этого класса

**Comment by DK-0x3** [comment]
Уже не помню почему 😅
